[{"Name":"Secure",
"Active":true,
"Scanner":2,
"Payloads":[" "],
"Encoder":[" "],
"UrlEncode":false,
"CharsToUrlEncode":"",
"Grep":["secure"],
"PayloadResponse":false,
"NotResponse":false,
"NotCookie":true,
"CaseSensitive":false,
"IsContentType":false,
"ContentType":"",
"IsResponseCode":false,
"ResponseCode":"",
"MatchType":1,
"IssueName":"Secure",
"IssueSeverity":"Low",
"IssueConfidence":"Certain",
"IssueDetail":"",
"RemediationDetail":"",
"IssueBackground":"",
"RemediationBackground":""}]
